adding simulating error

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -8,3 +8,6 @@ jobs:
     - uses: actions/checkout@v3
     - name: Run a simple GitHub action
       run: echo "This workflow ran successfully for the particular action"
+
+    - name: simulating error
+      run: echo"Error taking place"; exit 1
